name: glibc

on:
    push:
        branches:
            - master

    # Run tests for any PRs.
    pull_request:
    # Enable manual Starts
    workflow_dispatch:
    # Enable schedule building
    schedule:
        - cron:  "0 3 * * 3"
env:
    # Docker NAMESPACE
    NAMESPACE: moritztopp
jobs:
    # Run Tests for PRs
    test:
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'pull_request' }}
        steps:
            - uses: actions/checkout@v2

            - name: Log into registry
              run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u $NAMESPACE --password-stdin

            - name: Try to Build
              run: docker build . --file $GITHUB_WORKFLOW.Dockerfile --tag $NAMESPACE/${{ github.event.repository.name }}:$GITHUB_WORKFLOW
    # Build the Docker Image
    build:
        runs-on: ubuntu-latest
        if: ${{ github.event_name != 'pull_request' }}

        steps:
            - uses: actions/checkout@v2

            - name: Log into registry
              run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u $NAMESPACE --password-stdin

            - name: Pull from registry
              # If no Image exists, skip this (manual start)
              if: ${{ github.event_name != 'workflow_dispatch' }}
              run:  docker pull $NAMESPACE/${{ github.event.repository.name }}:$GITHUB_WORKFLOW

            - name: Build
              run: docker build . --file $GITHUB_WORKFLOW.Dockerfile --tag $NAMESPACE/${{ github.event.repository.name }}:$GITHUB_WORKFLOW

            - name: Push to registry
              run:  docker push $NAMESPACE/${{ github.event.repository.name }}:$GITHUB_WORKFLOW
